export const Products = [
    {
      id: 1,
      Description: "Automated Insights from your Google Analytics",
      img: "https://ph-files.imgix.net/c725987a-7180-4ecd-8e3e-07ce47a3c86d.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=80&h=80&fit=crop",
      date: "01/11/21",
      userId: 1,
      votes: 32,
      comment: 9,
      name:"sofy",
      monetization:"free",
      Category:"gaming"
    },
    {
      id: 2,
      img: "https://ph-files.imgix.net/c725987a-7180-4ecd-8e3e-07ce47a3c86d.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=80&h=80&fit=crop",
      Description: "Automated Insights from your Google Analytics",
      date: "02/11/21",
      userId: 2,
      votes: 2,
      comment: 1,
      name:"sofy",
      monetization:"free",
      Category:"gaming"
    },
    {
      id: 3,
      Description: "Automated Insights from your Google Analytics",
      img: "https://ph-files.imgix.net/c725987a-7180-4ecd-8e3e-07ce47a3c86d.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=80&h=80&fit=crop",
      date: "03/11/21",
      userId: 3,
      votes: 61,
      comment: 2,
      name:"sofy",
      monetization:"free",
      Category:"gaming"
    },
    {
      id: 4,
      Description: "Automated Insights from your Google Analytics",
      img: "https://ph-files.imgix.net/c725987a-7180-4ecd-8e3e-07ce47a3c86d.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=80&h=80&fit=crop",
      date: "4/11/21",
      userId: 4,
      votes: 7,
      comment: 3,
      name:"sofy",
      monetization:"free",
      Category:"gaming"
    },
    {
      id: 5,
      Description: "Automated Insights from your Google Analytics",
      img: "https://ph-files.imgix.net/c725987a-7180-4ecd-8e3e-07ce47a3c86d.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=80&h=80&fit=crop",
      date: "05/11/21",
      userId: 5,
      votes: 23,
      comment: 5,
      name:"sofy",
      monetization:"free",
      Category:"gaming"
    },
    {
      id: 6,
      Description: "Automated Insights from your Google Analytics",
      img: "https://ph-files.imgix.net/c725987a-7180-4ecd-8e3e-07ce47a3c86d.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=80&h=80&fit=crop",
      date: "06/11/21",
      userId: 6,
      votes: 44,
      comment: 6,
      name:"sofy",
      monetization:"free",
      Category:"gaming"
    },
    {
      id: 7,
      Description: "Automated Insights from your Google Analytics",
      img: "https://ph-files.imgix.net/c725987a-7180-4ecd-8e3e-07ce47a3c86d.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=80&h=80&fit=crop",
      date: "2 days ago",
      userId: 7,
      votes: 52,
      comment: 3,
      name:"sofy",
      monetization:"free",
      Category:"gaming"
    },
    {
      id: 8,
      Description: "Automated Insights from your Google Analytics",
      img: "https://ph-files.imgix.net/c725987a-7180-4ecd-8e3e-07ce47a3c86d.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=80&h=80&fit=crop",
      date: "07/11/21",
      userId: 8,
      votes: 15,
      comment: 1,
      name:"sofy",
      monetization:"free",
      Category:"gaming"
    },
    {
      id: 9,
      Description: "Automated Insights from your Google Analytics",
      img: "https://ph-files.imgix.net/c725987a-7180-4ecd-8e3e-07ce47a3c86d.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=80&h=80&fit=crop",
      date: "08/11/21",
      userId: 9,
      votes: 11,
      comment: 2,
      name:"sofy",
      monetization:"free",
      Category:"gaming"
    },
    {
      id: 10,
      Description: "Automated Insights from your Google Analytics",
      img: "https://ph-files.imgix.net/c725987a-7180-4ecd-8e3e-07ce47a3c86d.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=80&h=80&fit=crop",
      date: "09/11/21",
      userId: 10,
      votes: 104,
      comment: 12,
      name:"sofy",
      monetization:"free",
      Category:"gaming"
    },
  ];

