export const Products = [
    {
      id: 1,
      Description: "Automated Insights from your Google Analytics",
      img: "https://ph-files.imgix.net/c725987a-7180-4ecd-8e3e-07ce47a3c86d.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=80&h=80&fit=crop",
      date: "01/11/21",
      userId: 1,
      votes: 332,
      comment: 9,
      name:"sofy",
      monetization:"free",
      Category:"gaming",
      link:"https://www.producthunt.com/posts/grist-2",
    },
    {
      id: 2,
      img: "https://ph-files.imgix.net/d8d817e9-5de6-4499-825b-eff05a74a342.gif?auto=compress&fm=webp&codec=mozjpeg&cs=strip&w=80&h=80&fit=max&frame=1&dpr=2",
      Description: "Find out how the Market makes your Startup play by its rules",
      date: "02/11/21",
      userId: 2,
      votes: 222,
      comment: 16,
      name:"Is Your Startup Trapped in a Squid Game?",
      monetization:"free",
      Category:"Tech",
      link:"https://www.producthunt.com/posts/is-your-startup-trapped-in-a-squid-game"
    },
    {
      id: 3,
      Description: "Converting ad creatives, banners by artificial intelligence",
      img: "https://ph-files.imgix.net/7ca947a4-152d-4909-851b-25adaba41584.gif?auto=compress&fm=webp&codec=mozjpeg&cs=strip&w=80&h=80&fit=max&frame=1&dpr=2",
      date: "03/11/21",
      userId: 3,
      votes: 661,
      comment: 22,
      name:"AdCreative.ai",
      monetization:"free options",
      Category:"gaming",
      link:"https://www.producthunt.com/posts/adcreative-ai"
    },
    {
      id: 4,
      Description: "A private place for everything you care about.",
      img: "https://ph-files.imgix.net/c489041c-21e0-49b9-b917-5a6cb596e2d1.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=80&h=80&fit=crop&dpr=1",
      date: "4/11/21",
      userId: 4,
      votes: 710,
      comment: 31,
      name:"mymind",
      monetization:"free options",
      Category:"gaming",
      link:"https://www.producthunt.com/posts/mymind-82cba725-59f2-4f84-baf3-c1797165c44c"
    },
    {
      id: 5,
      Description: "The free Calendly alternative that makes scheduling personal",
      img: "https://ph-files.imgix.net/802a7883-8e21-4f77-806b-cfe2414500cf.gif?auto=compress&fm=webp&codec=mozjpeg&cs=strip&w=80&h=80&fit=max&frame=1&dpr=2",
      date: "05/11/21",
      userId: 5,
      votes: 230,
      comment: 52,
      name:"zcal",
      monetization:"free",
      Category:"gaming",
      link:"https://www.producthunt.com/posts/zcal"
    },
    {
      id: 6,
      Description: "The most complete NFT newsletter",
      img: "https://ph-files.imgix.net/7ab5e536-fbb4-4bc6-9c59-18559f5174e4.jpeg?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=80&h=80&fit=crop&dpr=1",
      date: "06/11/21",
      userId: 6,
      votes: 440,
      comment: 60,
      name:"This Week in NFTs",
      monetization:"free",
      Category:"gaming",
      link:"https://www.producthunt.com/posts/this-week-in-nfts-e5c0a55f-be42-473f-bed9-b5672e04d392"
    },
    {
      id: 7,
      Description: "Video platform for virtual selling",
      img: "https://ph-files.imgix.net/302a2c2c-84f2-4941-a8a4-9da25b9ca3f5.gif?auto=compress&fm=webp&codec=mozjpeg&cs=strip&w=80&h=80&fit=max&frame=1&dpr=2",
      date: "2 days ago",
      userId: 7,
      votes: 520,
      comment: 30,
      name:"VideoForm",
      monetization:"free",
      Category:"gaming",
      link:"https://www.producthunt.com/posts/videoform"
    },
    {
      id: 8,
      Description: "Helping the time-poor read more, through our newsletter",
      img: "https://ph-files.imgix.net/cde2b2c7-5f12-4f47-bc95-78cdbb92d27e.gif?auto=compress&fm=webp&codec=mozjpeg&cs=strip&w=80&h=80&fit=max&frame=1&dpr=2",
      date: "07/11/21",
      userId: 8,
      votes: 158,
      comment: 15,
      name:"The Chatty Mammoth",
      monetization:"free",
      Category:"gaming",
      link:"https://www.producthunt.com/posts/the-chatty-mammoth"
    },
    {
      id: 9,
      Description: "Mac utility for running scripts with keyboard shortcuts",
      img: "https://ph-files.imgix.net/291c7ea8-7311-4668-9819-9e8bcc54f546.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=80&h=80&fit=crop&dpr=1 1x, https://ph-files.imgix.net/291c7ea8-7311-4668-9819-9e8bcc54f546.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=80&h=80&fit=crop&dpr=2 2x, https://ph-files.imgix.net/291c7ea8-7311-4668-9819-9e8bcc54f546.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=80&h=80&fit=crop&dpr=3 3x",
      date: "08/11/21",
      userId: 9,
      votes: 114,
      comment: 20,
      name:"FastScripts 3",
      monetization:"free",
      Category:"gaming",
      link:'https://www.producthunt.com/posts/fastscripts-3'
    },
    {
      id: 10,
      Description: "Automated Insights from your Google Analytics",
      img: "https://ph-files.imgix.net/2321425f-651e-4ea5-8a94-03040ee09edb.gif?auto=compress&fm=webp&codec=mozjpeg&cs=strip&w=80&h=80&fit=max&frame=1&dpr=2",
      date: "09/11/21",
      userId: 10,
      votes: 704,
      comment: 121,
      name:"sofy",
      monetization:"free",
      Category:"gaming"
    },
  ];

